#ifndef FRACTIONLIB_GLOBAL_H
#define FRACTIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(FRACTIONLIB_LIBRARY)
#  define FRACTIONLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define FRACTIONLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // FRACTIONLIB_GLOBAL_H
